[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
buzzing_whirlpool = "Afgwr9kwhizNJLAjmygZXQ3gxxuXzmJ2HR3gJeRz1rW4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=d64ad269-f73b-4885-88d1-359e1faf2ae3"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
